config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  root "logs#index"

  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"

  get "logs/new_char"
  resources :logs
  post "logs/pre_new"
  get "logs/:id/preparing" => "logs#preparing", as: "log_preparing"
  get "logs/:id/logcontent" => "logs#log_content", as: "log_logContent"
  get "logs/:id/logview" => "logs#logview_content", as: "log_logviewContent"
  post "logs/:id/make_log_content" => "logs#make_log_content", as: "log_makeLogContent"

  resources :characters
  post "characters/create_pl"
  post "characters/:id/purge" => "characters#purge", as: "character_purge"

  resources :schedules
  resources :users

  get "*path", to: "application#page404", constraints: lambda { |req|
    !req.path.starts_with?("/rails/active_storage")
  }
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :game
  validates :date, presence: true
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @year = params.fetch(:year, Time.zone.today.year).to_i
    @month = params.fetch(:month, Time.zone.today.month).to_i
    start_date = Date.new(@year, @month, 1)
    end_date = start_date.end_of_month
    @calendars = []
    date = start_date
    until date > end_date do
      @calendars.push(date)
      date = date.next_day
    end
    @schedules = Game.joins(:schedules).select("games.*, schedules.*").where("date between ? and ?", start_date, end_date).order(Arel.sql("CASE WHEN games.name = 'リアル' THEN 0 ELSE 1 END"))
  end

  def new
    @year = params.fetch(:year, Time.zone.today.year).to_i
    @month = params.fetch(:month, Time.zone.today.month).to_i
    start_date = Date.new(@year, @month, 1)
    end_date = start_date.end_of_month
    @calendars = []
    date = start_date
    @game = Game.new()
    until date > end_date do
      @calendars.push(date)
      @game.schedules.new(date: date)
      date = date.next_day
    end
  end

  def create
    # @year = params.fetch(:year, Time.zone.today.year).to_i
    # @month = params.fetch(:month, Time.zone.today.month).to_i
    game = params.require(:game)
    responses = game.select { |k, v| k.start_with?("response") }.values
    @game = Game.new(name: game[:game])
    i=1
    responses.each do |res|
      @game.schedules.new(date: game[:yearMonth]+"-"+i.to_s, response: res)
      i+=1
    end
    if @game.save()
      redirect_to(schedules_path(year: @year, month: @month))
    end
  end

  def edit
      @year = params.fetch(:year, Time.zone.today.year).to_i
      @month = params.fetch(:month, Time.zone.today.month).to_i
      start_date = Date.new(@year, @month, 1)
      end_date = start_date.end_of_month
      @calendars = []
      date = start_date
      until date > end_date do
        @calendars.push(date)
        date = date.next_day
      end
    @game = Game.preload(:schedules).find(params[:id])
  end

  def update
    @year = params.fetch(:year, Time.zone.today.year).to_i
    @month = params.fetch(:month, Time.zone.today.month).to_i
    game = params[:game]
    responses = game.select { |k, v| k.start_with?("response") }.values
    @game = Game.preload(:schedules).find(params[:id])
    if @game.update(params.require(:game).slice(:name).permit(:name))
      i=1
      responses.each do |res|
        @game.schedules.find { |s| s.date.strftime("%Y-%m-%d") == game[:yearMonth]+"-"+("%02d" % i) }.update(params.require(:game).merge(response: res).slice(:response).permit(:response))
        i+=1
      end
      redirect_to(schedules_path(year: @year, month: @month))
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<% path = game[:id] ? schedule_path(game) : schedules_path(game) %>
<%= form_with model:game, url: path do |form| %>
    <%= form.month_field :yearMonth, {value: @calendars[0], hidden: true} %>
    <table>
        <tr>
            <th><%= Schedule.human_attribute_name(:calendar) %></th>
            <th colspan=5><%= form.text_field :game, value: game[:name] %></th>
        </tr>
        <% i=0 %>
        <% @calendars.each do |date| %>
            <% schedule = game.schedules.find{ |s| s.date==date } %>
            <tr>
                <th><%= date.strftime('%m/%d') %><%= "(#{["日", "月", "火", "水", "木", "金", "土"][date.wday]})" %></th>
                <td>
                    <%= form.label "response" << date.day.to_s << "_0", '㏠' %>
                    <%= form.radio_button "response" << date.day.to_s, '0', checked: schedule[:response]==0 %>
                </td>
                <td>
                    <%= form.label "response" << date.day.to_s << "_1", '夜' %>
                    <%= form.radio_button "response" << date.day.to_s, '1', checked: schedule[:response]==1 %>
                </td>
                <td>
                    <%= form.label "response" << date.day.to_s << "_2", '昼' %>
                    <%= form.radio_button "response" << date.day.to_s, '2', checked: schedule[:response]==2 %>
                </td>
                <td>
                    <%= form.label "response" << date.day.to_s << "_3", '×' %>
                    <%= form.radio_button "response" << date.day.to_s, '3', checked: !schedule[:response] || schedule[:response]==3 %>
                </td>
            </tr>
            <% i+=1 %>
        <% end %>
    </table>
    <%= form.submit %>
<% end %>

app/views/schedules/edit.html.erb
<%= stylesheet_link_tag "schedule_new", "data-turbo-track": "reload" %>

<h1><%= t '.title' %></h1>
<%= render "form", {game: @game} %>

app/views/schedules/index.html.erb
<%= stylesheet_link_tag "schedule_index", "data-turbo-track": "reload" %>

<h1><%= t '.title' %> <%= @calendars[0].strftime('%y/%m') %></h1>
<div class="hflex date_controll_button">
    <%= button_to "＜", schedules_path(), params:{year: @month>1?@year:@year-1, month: @month>1?@month-1:@month+11}, method: :get %>
    <%= button_to t("schedules.new.title"), new_schedule_path(), params:{year: @year, month: @month}, method: :get, form:{style:"flex:1;"} %>
    <%= button_to "＞", schedules_path(), params:{year: @month<12?@year:@year+1, month: @month<12?@month+1:@month-11}, method: :get %>
</div>
<% if @calendars %>
<div id="calendar">
    <table>
        <tr>
            <th><%= Schedule.human_attribute_name(:calendar) %></th>
            <% responses = {} %>
            <% schedules = @schedules.pluck(:name).uniq %>
            <% schedules.each do |schedule| %>
                <% responses[schedule]=@schedules.where(name: schedule).order(:date) %>
                <th><%= link_to schedule, edit_schedule_path(responses[schedule][0][:game_id], year:@year, month:@month) %></th>
            <% end %>
        </tr>
        <% i=0 %>
        <% @calendars.each do |date| %>
            <tr data-type="<%= 3 - schedules.reduce(3){ |sum,s| sum & responses[s][i][:response] } %>">
                <th><%= date.strftime('%m/%d') %><%= "(#{["日", "月", "火", "水", "木", "金", "土"][date.wday]})" %></th>
                <% schedules.each do |schedule| %>
                    <td data-type=<%= responses[schedule][i][:response] %>></td>
                <% end %>
                <% i+=1 %>
            </tr>
        <% end %>
    </table>
</div>
<% end %>

app/views/schedules/new.html.erb
<%= stylesheet_link_tag "schedule_new", "data-turbo-track": "reload" %>

<h1><%= t '.title' %></h1>
<%= render "form", {game: @game} %>