config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  root "logs#index"

  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"

  get "logs/new_char"
  resources :logs
  post "logs/pre_new"
  get "logs/:id/preparing" => "logs#preparing", as: "log_preparing"
  get "logs/:id/logcontent" => "logs#log_content", as: "log_logContent"
  get "logs/:id/logview" => "logs#logview_content", as: "log_logviewContent"
  post "logs/:id/make_log_content" => "logs#make_log_content", as: "log_makeLogContent"

  resources :characters
  post "characters/create_pl"
  post "characters/:id/purge" => "characters#purge", as: "character_purge"

  resources :schedules
  resources :users

  get "*path", to: "application#page404", constraints: lambda { |req|
    !req.path.starts_with?("/rails/active_storage")
  }
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :pl, class_name: "User", foreign_key: "pl_id"
  has_many :appear_pcs
  has_many :log, through: :appear_pcs
  has_many :nicknames
  accepts_nested_attributes_for :nicknames, allow_destroy: true
  validates :name, presence: true, uniqueness: true
  has_many_attached :images

  attr_accessor :text
end

app/controllers/characters_controller.rb
require "zlib"

class CharactersController < ApplicationController
  def index
    @pc = Character.joins(:pl).where(is_pc: true).select("characters.*, users.name AS pl_name").order(:pl_name)
    @npc = Character.joins(:pl).where(is_pc: false).select("characters.*, users.name AS pl_name").order(:pl_name)
    @pl = User.filtered_all.order(:name)
  end

  def new
    @pc = Character.new
    @pl = User.new
  end

  def create
    character_params = params.require(:character)
    character_params[:nicknames_attributes].each_key { |n| if character_params[:nicknames_attributes][n][:name]=="" then character_params[:nicknames_attributes][n][:_destroy]=true end }
    character_params[:compressed_text] = Zlib::Deflate.deflate(character_params[:text])
    character_params = character_params.permit(:name, :is_pc, :pl_id, :compressed_text, images: [], nicknames_attributes: [ :id, :name, :_destroy ])
    @character = User.find(character_params[:pl_id]).characters.new(character_params)

    pp @character
    if @character.save()
      redirect_to edit_character_path(@character[:id])
    else
      pp @character.errors.details
    end
  end

  def create_pl
    @pl = User.new(params.require(:user).permit(:name).merge(userid: "default", password: "default"))
    if @pl.save()
      @pl.update(userid: "default#{@pl.id}", password: "default#{@pl.id}")
      redirect_to new_character_path
    else
      pp @pl.errors.details
    end
  end

  def show
    @character = Character.find(params[:id])
    if @character.compressed_text.present?
      begin
        @character.text = Zlib::Inflate.inflate(@character.compressed_text).force_encoding("UTF-8")
      rescue Zlib::BufError => e
        # エラー時の処理。例えば空文字にするなど
        @character.text = ""
        Rails.logger.error("Error inflating compressed_text: #{e.message}")
      end
    else
      @character.text = ""
    end
    @md_text = markdown(@character.text)
  end

  def edit
    @character = Character.includes(images_attachments: :blob).find(params[:id])
    if @character.compressed_text.present?
      begin
        @character.text = Zlib::Inflate.inflate(@character.compressed_text).force_encoding("UTF-8")
      rescue Zlib::BufError => e
        # エラー時の処理。例えば空文字にするなど
        @character.text = ""
        Rails.logger.error("Error inflating compressed_text: #{e.message}")
      end
    else
      @character.text = ""
    end
  end

  def update
    character = Character.find(params[:id])
    character_params = params.require(:character)
    character_params[:nicknames_attributes].each_key { |n| if character_params[:nicknames_attributes][n][:name]=="" then character_params[:nicknames_attributes][n][:_destroy]=true end }
    character_params[:compressed_text] = Zlib::Deflate.deflate(character_params[:text])
    character_params = character_params.permit(:name, :is_pc, :pl_id, :compressed_text, images: [], nicknames_attributes: [ :id, :name, :_destroy ])
    if character.update(character_params)
      redirect_to edit_character_path(params[:id])
    else
      pp character.errors.details
    end
  end

  def purge
    character = Character.find(params[:id])
    image = character.images.find(params[:image_id])
    image.purge
    redirect_to(edit_character_path(params[:id]))
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with model: character, url: character[:id]?character_path(character):characters_path do |form| %>

    <div class="selectButton" id="select_ispc">
        <div class="selectButton_item <%= "selected" if character&.is_pc %>" data-value=true>
            <span>PC</span>
        </div>
        <div class="selectButton_item <%= "selected" if !character&.is_pc %>" data-value=false>
            <span>NPC</span>
        </div>
        <%= form.hidden_field :is_pc %>
    </div>
    <%= form.label :name, Character.human_attribute_name(:name) %>
    <%= form.text_field :name %>
    <%= form.label :pl_id, Character.human_attribute_name(:pl) %>
    <%= form.collection_select :pl_id, User.filtered_all.order(:name), :id, :name %>
    <%= form.label :nickname, Character.human_attribute_name(:nickname) %>
    <% character.nicknames.new %>
    <%= form.fields_for :nicknames do |nickname_form| %>
        <div class="nickname-fields">
            <%= nickname_form.hidden_field :id %>
            <%= nickname_form.text_field :name %>
        </div>
    <% end %>
    <%= form.label :text, Character.human_attribute_name(:text) %>
    <%= form.text_area :text %>
    <%= form.file_field :images, multiple: true %>
    <% character.images.each do |image| %>
        <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
    <% end %>
    <%= form.submit %>
<% end %>

<div class="illust_container">
<% character.images.each do |image| %>
    <div class="illust">
        <%= button_to character_purge_path(character, image_id: image.id), {method: :post, class:"close"} do %>
            <i class="bi bi-x"></i>
        <% end %>
        <%= image_tag(image) %>
    </div>
<% end %>
</div>

app/views/characters/edit.html.erb
<%= stylesheet_link_tag "character", "data-turbo-track": "reload" %>
<h1><%= t '.title' %></h1>

<%= render "form", {character: @character} %>

app/views/characters/index.html.erb
<h1><%= t '.title' %></h1>

<%= button_to t('characters.new.title'), new_character_path, method: :get %>

<div class="xflex gap">

    <div>
        <h2><%= t('default.pc') %></h2>
        <table>
            <tr>
                <th>
                    <%= Character.human_attribute_name(:name) %>
                </th>
                <th>
                    <%= Character.human_attribute_name(:pl) %>
                </th>
                <th style="width:calc(60px + 1em)"></th>
            </tr>
            <% @pc.each do |pc| %>
                <tr data-url="<%= character_path(pc.id) %>">
                    <td>
                        <%= pc.name %>
                    </td>
                    <td>
                        <%= pc.pl_name %>
                    </td>
                    <td style="width:calc(60px + 1em)">
                        <%= link_to edit_character_path(pc.id) do %>
                            <i class="bi bi-vector-pen"></i>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>

    <div>
        <h2><%= t('default.npc') %></h2>
        <table>
            <tr>
                <th>
                    <%= Character.human_attribute_name(:name) %>
                </th>
                <th>
                    <%= Character.human_attribute_name(:pl) %>
                </th>
                <th style="width:calc(60px + 1em)"></th>
            </tr>
            <% @npc.each do |npc| %>
                <tr data-url="<%= character_path(npc.id) %>">
                    <td>
                        <%= npc.name %>
                    </td>
                    <td>
                        <%= npc.pl_name %>
                    </td>
                    <td style="width:calc(60px + 1em)">
                        <%= link_to edit_character_path(npc.id) do %>
                            <i class="bi bi-vector-pen"></i>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>

    <div>
        <h2><%= t('default.pl') %></h2>
        <table>
            <tr>
                <th>
                    <%= User.human_attribute_name(:username) %>
                </th>
            </tr>
            <% @pl.each do |pl| %>
                <tr>
                    <td>
                        <%= pl.name %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>

</div>

app/views/characters/new.html.erb
<h1><%= t '.title' %></h1>
<%= render "form", {character: Character.new(is_pc: true)} %>

app/views/characters/show.html.erb
<%= stylesheet_link_tag "character_show", "data-turbo-track": "reload" %>

<%= button_to t("helpers.button.edit"), edit_character_path(@character.id), method: :get %>

<h1><%= @character.name %></h1>
<div id="images">
    <div class="left_arrow" onclick="send_page(0, event)"></div>
    <div class="right_arrow" onclick="send_page(1, event)"></div>
    <% i = 0 %>
    <% images = @character.images %>
    <% if images.length<=1 then images.concat(images,images) end %>
    <% if images.length<=2 then images.concat(images) end %>
    <% images.each do |image| %>
        <%= image_tag image, {class: i>0 ? "img_r" : i<0 ? "img_l" : "img_c" ,style: "order: #{i}"} %>
        <% i+=1 %>
        <% if i>images.length/2 then i-=images.length end %>
    <% end %>
</div>

<p>PL: <%= @character.pl.name %></p>
<%= sanitize(@md_text, tags: %w(div p span a br strong em u h1 h2 h3 h4 h5 h6 ul ol li button code pre blockquote table tbody tr td th hr), attributes: %w(style class href))  %>

<script>
    window.send_page_flag = true;
    function send_page(next, e){
        if(send_page_flag){
            send_page_flag = false;
            const d = next ? 1 : -1;
            const imgs = e.currentTarget.parentElement.querySelectorAll("img");
            for(img of imgs){
                img.style.order = Number(img.style.order) - d;
                if(img.style.order>imgs.length/2) img.style.order = Number(img.style.order) - imgs.length;
                if(img.style.order<=-imgs.length/2) img.style.order = Number(img.style.order) + imgs.length;
                img.classList.remove("img_l", "img_c", "img_r");
                img.classList.add(img.style.order<0 ? "img_l" : img.style.order==0 ? "img_c" : "img_r");
            }
            setTimeout(() => {
                send_page_flag = true;
            }, 500);
        }
    }
</script>