config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  root "logs#index"

  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"

  get "logs/new_char"
  resources :logs
  post "logs/pre_new"
  get "logs/:id/preparing" => "logs#preparing", as: "log_preparing"
  get "logs/:id/logcontent" => "logs#log_content", as: "log_logContent"
  get "logs/:id/logview" => "logs#logview_content", as: "log_logviewContent"
  post "logs/:id/make_log_content" => "logs#make_log_content", as: "log_makeLogContent"

  resources :characters
  post "characters/create_pl"
  post "characters/:id/purge" => "characters#purge", as: "character_purge"

  resources :schedules
  resources :users

  get "*path", to: "application#page404", constraints: lambda { |req|
    !req.path.starts_with?("/rails/active_storage")
  }
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :gm, class_name: "User"
  has_many :log_contents
  has_many :appear_pcs
  has_many :pcs, through: :appear_pcs, source: :character
  validates :name, presence: true
  validates :date, presence: true
  validates :gm, presence: true
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @logs = Log.preload(:gm, :appear_pcs).all.order(:date)
  end

  def pre_new
    text = params[:file].read
    text.force_encoding(Encoding::UTF_8)
    File.write("public/logfile/temp.html", text, encoding: Encoding::UTF_8)
    redirect_to(new_log_path(filename: params[:file].original_filename))
  end
  def new
    if !File.exist?("public/logfile/temp.html") then redirect_to(logs_path) end
    @filename = params[:filename]
    @log = Log.new
  end
  def create
    gm = User.find(params.require(:log)[:gm])
    log_params = params.require(:log).slice(:name, :date, :hidden, :pc_ids).permit(:name, :date, :hidden, pc_ids: [])
    log_params[:pc_ids].reject!(&:blank?)
    @log = gm.logs.new(log_params)
    if @log.save
      File.rename("public/logfile/temp.html", "public/logfile/#{@log.id}.html")
      CreateLogcontentsJob.perform_later(current_user.id, @log.id)
      redirect_to logs_path, notice: "HTMLファイルの処理をバックグラウンドで実行しています"
    else
      pp @log.errors.details
      redirect_to(new_log_path)
    end
  end

  def edit
    @log = Log.find(params[:id])
  end

  def update
    log_params = params.require(:log).slice(:name, :date, :gm, :pc_ids).permit(:name, :date, :gm, pc_ids: [])
    log_params[:gm] = User.find(params.require(:log)[:gm])
    log_params[:pc_ids].reject!(&:blank?)
    @log = Log.find(params[:id])
    @pcs = @log.appear_pcs
    if @log.update(log_params)
      redirect_to(logs_path)
    else
      pp @log.errors.details
      redirect_to(edit_log_path(params[:id]))
    end
  end

  def destroy
  end

  def show
    @id = params[:id]
    @log = Log.find(@id)
    @page = (params[:page] || 1).to_i
    @log_content = @log.log_contents.find_by(index: @page)
  end

  def log_content
    @id = params[:id]
    @page = params[:page].to_i
    log = Log.find(@id)
    @log_content = log.log_contents.find_by(index: @page)
    char = nil
    author = @log_content[:author].gsub(/[[:space:]]/, "")
    char = Character.find_by("REGEXP_REPLACE(name, '\s+', '') = ?", author)
    char ||= Nickname.find_by("REGEXP_REPLACE(name, '\s+', '') = ?", author)&.character
    if @log_content.present?
      render json: {
        author: @log_content[:author],
        color: @log_content[:color],
        tab: @log_content[:tab],
        content: @log_content[:content],
        images: char ? char.images&.map { |image| url_for(image) } : "",
        char: char
      }
    else
      redirect_to(log_preparing_path(@id))
    end
  end

  $log_size = 40

  def logview_content
    @id = params[:id]
    log_page = params[:page].to_i
    @logcontents = Log.find(@id).log_contents.where(index: log_page-($log_size-1)/2 .. log_page+$log_size/2).order(:index)
    pp @logcontents
    if @logcontents.length != 0
      render partial: "logcontent"
    else
      render plain: ""
    end
  end

  def preparing # get
    @id = params[:id]
    unless @id =~ /\A\d+\z/ then redirect_to(logs_path) end
    file_path = Rails.public_path.join("logfile/#{@id}.html").cleanpath
    # brakeman -ignore
    @file_content = File.read(file_path)
  end

  def make_log_content # post
    @id = params[:id]
    if !Log.find(@id).log_contents.exists?(index: params[:index])
      Log.find(@id).log_contents.create(params.slice(:index, :color, :tab, :author, :content).permit(:index, :color, :tab, :author, :content))
    else
      Log.find(@id).log_contents.find_by(index: params[:index]).update(params.slice(:color, :tab, :author, :content).permit(:color, :tab, :author, :content))
    end
    head(:created)
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_logcontent.html.erb
<% @logcontents.each do |logcontent| %>
    <div class="logcontents_item" style="--color:<%= logcontent[:color] %>;" data-page="<%= logcontent[:index] %>">
        <div class="logcontents_colorbar"></div>
        <div class="logcontents_content">
            <div class="logcontents_content_name">
                <%= logcontent[:index] %>. <%= logcontent[:author] %> [<%= logcontent[:tab] %>]
            </div>
            <div class="logcontents_content_text">
                <%= simple_format(logcontent[:content]) %>
            </div>
        </div>
    </div>
    <hr>
<% end %>

app/views/logs/edit.html.erb
<h1><%= t '.title' %></h1>
<%= form_with model: @log, url: log_path(@log) do |form| %>
    <%= form.label :name, Log.human_attribute_name(:name) %>
    <%= form.text_field :name %>
    <%= form.label :date, Log.human_attribute_name(:date) %>
    <%= form.date_field :date %>
    <%= form.label :gm, Log.human_attribute_name(:gm) %>
    <%= form.collection_select :gm, User.all, :id, :name, {include_blank: true, selected: @log.gm.id} %>
    <%= form.label :pc_ids, Log.human_attribute_name(:pc) %>
    <%= form.collection_select :pc_ids, Character.joins(:pl).where(is_pc: true).select("characters.*, users.name AS pl_name").order(:pl_name), :id, :name, {selected: @log.pcs.map { |pc| pc.id }}, multiple: true %>
    <div>
        <%= form.label :hidden %>
        <%= form.check_box :hidden %>
    </div>
    <%= form.submit %>
<% end %>

app/views/logs/index.html.erb
<%= stylesheet_link_tag "log_index", "data-turbo-track": "reload" %>

<h1><%= t '.title' %></h1>
<% if @logs %>

<div class="selectButton" id="select_logvisible">
    <div class="selectButton_item selected" data-value=true>
        <i class="bi bi-eye-fill"></i>
    </div>
    <div class="selectButton_item" data-value=false>
        <i class="bi bi-eye-slash"></i>
    </div>
    <input type="hidden" value=true>
</div>

<table class="pc_loglist">
    <tr>
        <th><%= Log.human_attribute_name(:name) %></th>
        <th><%= Log.human_attribute_name(:date) %></th>
        <th><%= Log.human_attribute_name(:gm) %></th>
        <th colspan=4><%= Log.human_attribute_name(:pc) %></th>
        <th></th>
    </tr>
    <% @logs.each do |log| %>
    <tr data-url="<%= log_path(log.id) %>" class="<%= log.hidden ? "hidden" : "visible" %>" style="view-transition-name:log_<%=log.id%>">
        <td><%= log.name %></td>
        <td><%= log.date %></td>
        <td><%= log.gm.name %></td>
        <% log.pcs.each do |pc| %>
            <td><%= pc.name %></td>
        <% end %>
        <% (4-log.pcs.size).times do %>
            <td></td>
        <% end %>
        <td>
            <%= link_to edit_log_path(log.id) do %>
                <i class="bi bi-vector-pen"></i>
            <% end %>
        </td>
    </tr>
    <% end %>
</table>

<ul class="sp_loglist table">
    <% @logs.each do |log| %>
    <li data-url="<%= log_path(log.id) %>" class="vflex <%= log.hidden ? "hidden" : "visible" %>" style="view-transition-name:log_<%=log.id%>">
        <div class="hflex" style="flex-grow:1;">
            <span class="log_name" style="flex:1">
                <%= log.name %>
            </span>
            <%= link_to edit_log_path(log.id) do %>
                <i class="bi bi-vector-pen"></i>
            <% end %>
        </div>
        <span class="log_member">
            <%= log.gm.name %> / 
            <% log.pcs.each do |pc| %>
                <%= pc.name.gsub(/\s/, "") %>
            <% end %>
        </span>
    </li>
    <% end %>
</ul>

<% else %>
    <p><%= t(".message") %></p>
<% end %>
<div style="display:none;">
    <%= form_with url: logs_pre_new_path, id: "dropFileForm", data: { target: "logs--index.form" } do |form| %>
        <%= form.file_field :file, data: { target: "logs--index.fileInput" } %>
        <%= form.submit %>
    <% end %>
</div>

app/views/logs/new.html.erb
<h1><%= t '.title' %></h1>
<span><%= @filename %></span>
<%= form_with model: @log, url: logs_path do |form| %>
    <%= form.label :name, Log.human_attribute_name(:name) %>
    <%= form.text_field :name %>
    <%= form.label :date, Log.human_attribute_name(:date) %>
    <%= form.date_field :date %>
    <%= form.label :gm, Log.human_attribute_name(:gm) %>
    <%= form.collection_select :gm, User.filtered_all, :id, :name, include_blank: true %>
    <%= form.label :pc_ids, Log.human_attribute_name(:pc) %>
    <%= form.collection_select :pc_ids, Character.joins(:pl).where(is_pc: true).select("characters.*, users.name AS pl_name").order(:pl_name), :id, :name, {}, multiple: true %>
    <div>
        <%= form.label :hidden %>
        <%= form.check_box :hidden %>
    </div>
    <%= form.submit %>
<% end %>

app/views/logs/preparing.html.erb
<%= stylesheet_link_tag "preparing", "data-turbo-track": "reload" %>

<div class="mask">
    <span>準備中</span>
    <progress value="0" max=""></progress>
</div>

<div id="html_container">
    <%= sanitize(@file_content, tags: %w(p span br), attributes: %w(style)) %>
</div>

<script>
    window.addEventListener("turbo:load", () => {
        console.log(document.getElementById("html_container"))
        const comments = document.getElementById("html_container").querySelectorAll("p");
        let progress = document.querySelector(".mask>progress");
        progress.max = comments.length;
        logContent_send(0, comments, ()=>{progress.value++});
    })

    const logContent_send = (n, a, func) => {
        let comment = a[n];
        let temp = comment.querySelectorAll("span");
        let form = new FormData();
        form.set("index", n+1);
        form.set("color", comment.style.color);
        form.set("tab", temp[0].textContent.match(/(?<=\[).+(?=\])/)[0]);
        form.set("author", temp[1].textContent);
        form.set("content", temp[2].innerText.replace(/^\s+/mg, "").replace(/\n$/, ""));
        
        fetch("<%= log_makeLogContent_path(@id) %>", {
            method: 'POST',
            headers: { 'X-CSRF-Token': getCsrfToken() },
            body: form
        }).then(res=>{
            func();
            if(n + 1 < a.length){
                logContent_send(n+1, a, func);
            }else{
                location.href = "<%= log_path(@id) %>"
            }
        })
    }

    const getCsrfToken = () => {
      const metas = document.getElementsByTagName('meta');
      for (let meta of metas) {
          if (meta.getAttribute('name') === 'csrf-token') {
              return meta.getAttribute('content');
          }
      }
      return '';
    }
</script>

app/views/logs/show.html.erb
<% content_for :title, @log_content.log[:name] %>

<%= stylesheet_link_tag "log_show", "data-turbo-track": "reload" %>

<div id="logview" style="view-transition-name:log_<%=@log_content.log[:id]%>">
    <div id="logview_container"></div>
</div>


<script>
    //メイン台詞枠
    {
        let page = <%= @page %>;
        const SCROLLRANGE = 200;
        const logview_elem = document.getElementById("logview");
        const logview_container_elem = document.getElementById("logview_container");
        let scrolltop_flag = true;
        let scrollbottom_flag = true;

        const getLogview = async (page) => {
            let res = await fetch(`/logs/<%= @id %>/logview?page=${page}`);
            let text = await res.text();
            console.log(text);
            
            return text;
        }

            scrolltop_flag = true;
            scrollbottom_flag = true;
            getLogview(page).then(res=>{
                logview_container_elem.innerHTML = res;
                logview_container_elem.querySelector(`[data-page="${page}"]+hr`).scrollIntoView({ block: "end" });
            });

        logview_elem.addEventListener("scroll", ()=>{
            if(logview_elem.scrollTop < SCROLLRANGE && scrolltop_flag){
                scrolltop_flag = false;
                getLogview(logview_container.querySelector(".logcontents_item:first-of-type").dataset.page-21).then(res=>{
                    const oldTop = document.documentElement.scrollTop;
                    const oldHeight = logview_elem.scrollHeight;
                    logview_container_elem.insertAdjacentHTML('afterbegin', res);
                    const diffHeight = logview_elem.scrollHeight - oldHeight;
                    logview_container_elem.scrollTop = oldTop - diffHeight;
                    if(logview_container.querySelector(".logcontents_item:first-of-type").dataset.page!=1) scrolltop_flag = true;
                }).catch(err => {
                    scrolltop_flag = true;
                    console.Error(err);
                })
            }
            if((logview_elem.scrollHeight - logview_elem.scrollTop - logview_elem.clientHeight) < SCROLLRANGE && scrollbottom_flag){
                scrollbottom_flag = false;
                getLogview(Number(logview_container.querySelector(".logcontents_item:last-of-type").dataset.page)+20).then(res=>{
                    logview_container_elem.insertAdjacentHTML('beforeend', res);
                    if(res != "") scrollbottom_flag = true;
                }).catch(err => {
                    scrolltop_flag = true;
                    console.Error(err);
                })
            }
        })
    }
</script>