config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  root "logs#index"

  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"

  get "logs/new_char"
  resources :logs
  post "logs/pre_new"
  get "logs/:id/preparing" => "logs#preparing", as: "log_preparing"
  get "logs/:id/logcontent" => "logs#log_content", as: "log_logContent"
  get "logs/:id/logview" => "logs#logview_content", as: "log_logviewContent"
  post "logs/:id/make_log_content" => "logs#make_log_content", as: "log_makeLogContent"

  resources :characters
  post "characters/create_pl"
  post "characters/:id/purge" => "characters#purge", as: "character_purge"

  resources :schedules
  resources :users

  get "*path", to: "application#page404", constraints: lambda { |req|
    !req.path.starts_with?("/rails/active_storage")
  }
end

app/views/layouts/_footer.html.erb
<footer>
    <div onclick="history.back()">
        <i class="bi bi-caret-left-fill"></i>
    </div>
    <div data-url="/">
        <i class="bi bi-house"></i>
    </div>
    <div data-url="/characters">
        <i class="bi bi-people-fill"></i>
    </div>
    <div data-url="/schedules">
        <i class="bi bi-calendar-week"></i>
    </div>
    <div data-url="/users">
        <i class="bi bi-person-circle"></i>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav>
    <div class="nav_menubutton">
        <div class="nav_menubutton_bar"></div>
    </div>
    <%= link_to "PORT", logs_path, class: "nav_logo" %>
    <div style="flex:1"></div>
    <% if logged_in? %>
        <button onclick="document.getElementById('notion_container').classList.toggle('open')">
            notion
        </button>
        <div id="notion_container" class="">
        </div>

        <span>[ <%= current_user.name %> ]</span>
        <%= button_to "logout", logout_path, method: :delete %>
    <% end %>
</nav>

app/views/layouts/_sidebar.html.erb
<%= link_to t("logs.index.title"), logs_path %>
<%= link_to t("characters.index.title"), characters_path %>
<%= link_to t("schedules.index.title"), schedules_path %>
<%= link_to t("users.index.title"), users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html colorSchemeType=<%= current_user&.appearanceMode || 0 %>>
  <head>
    <title><%= content_for(:title) || "Logformatter" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,viewport-fit=cover,user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="white" media="(prefers-color-scheme: light)">
    <meta name="theme-color" content="black" media="(prefers-color-scheme: dark)">
    <meta name="background-color" content="white" media="(prefers-color-scheme: light)">
    <meta name="background-color" content="black" media="(prefers-color-scheme: dark)">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon_180.png">
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield(:js) %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <% if !request.referer&.include?(root_url) %>
      <div id="startup_mask">
        <h1>PORT</h1>
        <span>Primary Operator's Routing Terminal</span>
      </div>
    <% end %>
    <div id="loading_mask" class="hidden">
      <div id="loader"></div>
    </div>
    <main data-controller="<%= controller_path + "--" + action_name %>">
      <div id="sidebar" class="open<%= if default_hidden? then " default-hidden" end %>">
        <div id="sidebar_container">
          <%= render "layouts/sidebar" %>
        </div>
      </div>
      <div id="main">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>